# Automatic Makefile made by make4js by N.J.M.

fgl_obj1 =  \
	 custlist.$(4GLOBJ) \
	 orders.$(4GLOBJ) \
	 stocklist.$(4GLOBJ)

fgl_frm1 =  \
	 custlist.$(FRMOBJ) \
	 orderform.$(FRMOBJ) \
	 stocklist.$(FRMOBJ)

#depend::
#	echo "making depends";  cd lib ; ./link_lib

PRG1=orders.42r

include ../etc/Make_fjs.inc
