# Automatic Makefile made by make4js by N.J.M.

fgl_obj1 =  \
	 cust_lib.$(4GLOBJ) \
	 cust_stub.$(4GLOBJ)

fgl_frm1 =  \
	 manycust.$(FRMOBJ)

#depend::
#	echo "making depends";  cd lib ; ./link_lib

PRG1=arrays.42r

include ../etc/Make_fjs.inc
