# Automatic Makefile made by make4js by N.J.M.

fgl_obj1 =  \
	 custmain.$(4GLOBJ) \
	 custquery.$(4GLOBJ)

fgl_frm1 =  \
	 custform.$(FRMOBJ)

#depend::
#	echo "making depends";  cd lib ; ./link_lib

PRG1=query.42r

include ../etc/Make_fjs.inc
