# Automatic Makefile made by make4js by N.J.M.

export FGLRESOURCEPATH=./etc
export FGLPROFILE=./etc/fr_profile

fgl_obj1 =  \
	 main.$(4GLOBJ) \
	 pretty_lab.$(4GLOBJ) \
	 shownode.$(4GLOBJ) \
	 about.$(4GLOBJ)

fgl_frm1 =  \
	 form.$(FRMOBJ)

PRG1=getGDCcfg.42r

include ./Make_fjs.inc
